[package]
name = "group-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
cli-table = "0.4"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"
colored = "2.0"
