name: CI rust group generator

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check for unverified commits
      uses: nadock/verified_commits_check@v1
      
    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test --verbose

    - name: log into GitHub container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: downcase REPO
      run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
          
    - name: Build Project
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
            ghcr.io/${{ env.repo }}:latest
            ghcr.io/${{ env.repo }}:${{ github.run_number }}
